name: twyne-cli

ethereum:
  mainnet:
    default_provider: node
    gas_limit:
      auto:
        multiplier: 1.5
    base_fee_multiplier: 1.4

networks:
  custom:
    - name: megaeth
      chain_id: 4326
      ecosystem: ethereum
      gas_limit: auto
      base_fee_multiplier: 1.4
